/* Allegro datafile object indexes, produced by grabber v3.0 + WIP */
/* Datafile: d:\psyk\redpixel\blood.dat */
/* Date: Thu Jul  9 17:57:14 1998 */
/* Do not hand edit! */

#define _COPYR_                          0        /* DATA */
#define A_ARMOUR                         1        /* BMP  */
#define A_ARROW                          2        /* BMP  */
#define A_BACKPACK                       3        /* BMP  */
#define A_BLOODLUST                      4        /* BMP  */
#define A_BLOODLUST1                     5        /* BMP  */
#define A_BLOODLUST2                     6        /* BMP  */
#define A_BLOODLUST3                     7        /* BMP  */
#define A_BLOODLUST4                     8        /* BMP  */
#define A_BLOODLUST5                     9        /* BMP  */
#define A_BULLET                         10       /* BMP  */
#define A_CHICKEN                        11       /* BMP  */
#define A_COKE                           12       /* BMP  */
#define A_GOGGLES                        13       /* BMP  */
#define A_GOGGLES1                       14       /* BMP  */
#define A_GOGGLES2                       15       /* BMP  */
#define A_ROCKET                         16       /* BMP  */
#define A_SHELL                          17       /* BMP  */
#define BACKDROP                         18       /* BMP  */
#define BLOD0                            19       /* BMP  */
#define BLOD1                            20       /* BMP  */
#define BLOD2                            21       /* BMP  */
#define BLOD3                            22       /* BMP  */
#define BLOD4                            23       /* BMP  */
#define BLOD5                            24       /* BMP  */
#define BLOD6                            25       /* BMP  */
#define BLOD7                            26       /* BMP  */
#define BLOD8                            27       /* BMP  */
#define BLOD9                            28       /* BMP  */
#define BLODA                            29       /* BMP  */
#define BLODB                            30       /* BMP  */
#define BLODC                            31       /* BMP  */
#define BLODD                            32       /* BMP  */
#define BLODE                            33       /* BMP  */
#define D_ARM0                           34       /* BMP  */
#define D_ARM1                           35       /* BMP  */
#define D_ARM2                           36       /* BMP  */
#define D_ARM3                           37       /* BMP  */
#define D_ARM4                           38       /* BMP  */
#define D_ARM5                           39       /* BMP  */
#define D_ARM6                           40       /* BMP  */
#define D_ARM7                           41       /* BMP  */
#define D_ARM8                           42       /* BMP  */
#define D_ARM9                           43       /* BMP  */
#define D_ARMA                           44       /* BMP  */
#define D_ARMB                           45       /* BMP  */
#define D_BACK0                          46       /* BMP  */
#define D_BACK1                          47       /* BMP  */
#define D_BACK2                          48       /* BMP  */
#define D_BACK3                          49       /* BMP  */
#define D_BACK4                          50       /* BMP  */
#define D_BACK5                          51       /* BMP  */
#define D_BACK6                          52       /* BMP  */
#define D_BACK7                          53       /* BMP  */
#define D_BACK8                          54       /* BMP  */
#define D_BACK9                          55       /* BMP  */
#define D_HEAD0                          56       /* BMP  */
#define D_HEAD1                          57       /* BMP  */
#define D_HEAD2                          58       /* BMP  */
#define D_HEAD3                          59       /* BMP  */
#define D_HEAD4                          60       /* BMP  */
#define D_HEAD5                          61       /* BMP  */
#define D_HEAD6                          62       /* BMP  */
#define D_HEAD7                          63       /* BMP  */
#define D_HEAD8                          64       /* BMP  */
#define D_HEAD9                          65       /* BMP  */
#define D_HEADA                          66       /* BMP  */
#define D_HEADB                          67       /* BMP  */
#define D_HEADC                          68       /* BMP  */
#define D_HEADD                          69       /* BMP  */
#define D_IMPALE000                      70       /* BMP  */
#define D_IMPALE001                      71       /* BMP  */
#define D_IMPALE002                      72       /* BMP  */
#define D_IMPALE003                      73       /* BMP  */
#define D_IMPALE004                      74       /* BMP  */
#define D_IMPALE005                      75       /* BMP  */
#define D_IMPALE006                      76       /* BMP  */
#define D_IMPALE007                      77       /* BMP  */
#define D_IMPALE008                      78       /* BMP  */
#define D_IMPALE009                      79       /* BMP  */
#define D_IMPALE010                      80       /* BMP  */
#define D_IMPALE011                      81       /* BMP  */
#define D_IMPALE012                      82       /* BMP  */
#define D_IMPALE013                      83       /* BMP  */
#define D_IMPALE014                      84       /* BMP  */
#define D_IMPALE015                      85       /* BMP  */
#define D_IMPALE016                      86       /* BMP  */
#define D_IMPALE017                      87       /* BMP  */
#define D_IMPALE018                      88       /* BMP  */
#define D_IMPALE019                      89       /* BMP  */
#define D_LEGS000                        90       /* BMP  */
#define D_LEGS001                        91       /* BMP  */
#define D_LEGS002                        92       /* BMP  */
#define D_LEGS003                        93       /* BMP  */
#define D_LEGS004                        94       /* BMP  */
#define D_LEGS005                        95       /* BMP  */
#define D_LEGS006                        96       /* BMP  */
#define D_LEGS007                        97       /* BMP  */
#define D_LEGS008                        98       /* BMP  */
#define D_LEGS009                        99       /* BMP  */
#define D_LEGS010                        100      /* BMP  */
#define D_LEGS011                        101      /* BMP  */
#define D_LEGS012                        102      /* BMP  */
#define D_LEGS013                        103      /* BMP  */
#define D_LEGS014                        104      /* BMP  */
#define D_LEGS015                        105      /* BMP  */
#define D_LEGS016                        106      /* BMP  */
#define D_LEGS017                        107      /* BMP  */
#define GAMEPAL                          108      /* PAL  */
#define HEART1                           109      /* BMP  */
#define HEART2                           110      /* BMP  */
#define HEART3                           111      /* BMP  */
#define J_ARROW                          112      /* BMP  */
#define J_KNIFE                          113      /* BMP  */
#define J_MINE1                          114      /* BMP  */
#define J_MINE2                          115      /* BMP  */
#define J_ROCKET                         116      /* BMP  */
#define L_EXPLO                          117      /* BMP  */
#define L_SPOT                           118      /* BMP  */
#define L_SPOTB                          119      /* BMP  */
#define MINI                             120      /* FONT */
#define P_BODY                           121      /* BMP  */
#define P_BOW0                           122      /* BMP  */
#define P_BOW1                           123      /* BMP  */
#define P_BOW2                           124      /* BMP  */
#define P_BOW3                           125      /* BMP  */
#define P_BOWB0                          126      /* BMP  */
#define P_BOWB1                          127      /* BMP  */
#define P_BOWB2                          128      /* BMP  */
#define P_BOWB3                          129      /* BMP  */
#define P_KNIFE0                         130      /* BMP  */
#define P_KNIFE1                         131      /* BMP  */
#define P_KNIFE2                         132      /* BMP  */
#define P_KNIFE3                         133      /* BMP  */
#define P_KNIFEB0                        134      /* BMP  */
#define P_KNIFEB1                        135      /* BMP  */
#define P_KNIFEB2                        136      /* BMP  */
#define P_KNIFEB3                        137      /* BMP  */
#define P_LEG0                           138      /* BMP  */
#define P_LEG1                           139      /* BMP  */
#define P_LEG2                           140      /* BMP  */
#define P_LEG3                           141      /* BMP  */
#define P_M160                           142      /* BMP  */
#define P_M161                           143      /* BMP  */
#define P_M162                           144      /* BMP  */
#define P_M163                           145      /* BMP  */
#define P_M16B0                          146      /* BMP  */
#define P_M16B1                          147      /* BMP  */
#define P_M16B2                          148      /* BMP  */
#define P_M16B3                          149      /* BMP  */
#define P_MINI0                          150      /* BMP  */
#define P_MINI1                          151      /* BMP  */
#define P_MINI2                          152      /* BMP  */
#define P_MINI3                          153      /* BMP  */
#define P_MINIB0                         154      /* BMP  */
#define P_MINIB1                         155      /* BMP  */
#define P_MINIB2                         156      /* BMP  */
#define P_MINIB3                         157      /* BMP  */
#define P_PISTOL0                        158      /* BMP  */
#define P_PISTOL1                        159      /* BMP  */
#define P_PISTOL2                        160      /* BMP  */
#define P_PISTOL3                        161      /* BMP  */
#define P_PISTOLB0                       162      /* BMP  */
#define P_PISTOLB1                       163      /* BMP  */
#define P_PISTOLB2                       164      /* BMP  */
#define P_PISTOLB3                       165      /* BMP  */
#define P_ROCKET0                        166      /* BMP  */
#define P_ROCKET1                        167      /* BMP  */
#define P_ROCKET2                        168      /* BMP  */
#define P_ROCKET3                        169      /* BMP  */
#define P_ROCKETB0                       170      /* BMP  */
#define P_ROCKETB1                       171      /* BMP  */
#define P_ROCKETB2                       172      /* BMP  */
#define P_ROCKETB3                       173      /* BMP  */
#define P_SHOTGUN0                       174      /* BMP  */
#define P_SHOTGUN1                       175      /* BMP  */
#define P_SHOTGUN2                       176      /* BMP  */
#define P_SHOTGUN3                       177      /* BMP  */
#define P_SHOTGUNB0                      178      /* BMP  */
#define P_SHOTGUNB1                      179      /* BMP  */
#define P_SHOTGUNB2                      180      /* BMP  */
#define P_SHOTGUNB3                      181      /* BMP  */
#define P_UZI0                           182      /* BMP  */
#define P_UZI1                           183      /* BMP  */
#define P_UZI2                           184      /* BMP  */
#define P_UZI3                           185      /* BMP  */
#define P_UZIB0                          186      /* BMP  */
#define P_UZIB1                          187      /* BMP  */
#define P_UZIB2                          188      /* BMP  */
#define P_UZIB3                          189      /* BMP  */
#define PLACE1                           190      /* BMP  */
#define RESPAWN0                         191      /* BMP  */
#define RESPAWN1                         192      /* BMP  */
#define RESPAWN2                         193      /* BMP  */
#define RESPAWN3                         194      /* BMP  */
#define RESPAWN4                         195      /* BMP  */
#define RESPAWN5                         196      /* BMP  */
#define RESPAWN6                         197      /* BMP  */
#define T_BAR                            198      /* BMP  */
#define T_BLA                            199      /* BMP  */
#define T_BLU                            200      /* BMP  */
#define T_CRATE                          201      /* BMP  */
#define T_GRE                            202      /* BMP  */
#define T_LAD                            203      /* BMP  */
#define T_METAL                          204      /* BMP  */
#define T_PUR                            205      /* BMP  */
#define T_RED                            206      /* BMP  */
#define T_SPIKE                          207      /* BMP  */
#define T_WOOD                           208      /* BMP  */
#define TITLE                            209      /* BMP  */
#define UNREAL                           210      /* FONT */
#define W_BOW                            211      /* BMP  */
#define W_KNIFE                          212      /* BMP  */
#define W_M16                            213      /* BMP  */
#define W_MINE                           214      /* BMP  */
#define W_MINI                           215      /* BMP  */
#define W_PISTOL                         216      /* BMP  */
#define W_ROCKET                         217      /* BMP  */
#define W_SHOTGUN                        218      /* BMP  */
#define W_UZI                            219      /* BMP  */
#define WAV_ARR                          220      /* SAMP */
#define WAV_ARR2                         221      /* SAMP */
#define WAV_ARR3                         222      /* SAMP */
#define WAV_ARR4                         223      /* SAMP */
#define WAV_ARR5                         224      /* SAMP */
#define WAV_ARR6                         225      /* SAMP */
#define WAV_BOW                          226      /* SAMP */
#define WAV_DEAD1                        227      /* SAMP */
#define WAV_DEAD2                        228      /* SAMP */
#define WAV_DEAD3                        229      /* SAMP */
#define WAV_DEAD4                        230      /* SAMP */
#define WAV_DEAD5                        231      /* SAMP */
#define WAV_EXPLODE                      232      /* SAMP */
#define WAV_EXPLODEBAR                   233      /* SAMP */
#define WAV_INCOMING                     234      /* SAMP */
#define WAV_KNIFE                        235      /* SAMP */
#define WAV_LETSPARTY                    236      /* SAMP */
#define WAV_M16                          237      /* SAMP */
#define WAV_MINE                         238      /* SAMP */
#define WAV_MINIGUN                      239      /* SAMP */
#define WAV_PICKUP                       240      /* SAMP */
#define WAV_RIC                          241      /* SAMP */
#define WAV_RIC2                         242      /* SAMP */
#define WAV_ROCKET                       243      /* SAMP */
#define WAV_SELECT                       244      /* SAMP */
#define WAV_SHOTGUN                      245      /* SAMP */
#define WAV_TYPE                         246      /* SAMP */
#define WAV_UZI                          247      /* SAMP */
#define X_EXPLO0                         248      /* BMP  */
#define X_EXPLO1                         249      /* BMP  */
#define XHAIR                            250      /* BMP  */

