/* Allegro datafile object indexes, produced by grabber v3.0 + WIP */
/* Datafile: d:\psyk\wacko\blood.dat */
/* Date: Sun Jun 28 17:06:04 1998 */
/* Do not hand edit! */

#define _COPYR_                          0        /* DATA */
#define A_ARMOUR                         1        /* BMP  */
#define A_ARROW                          2        /* BMP  */
#define A_BACKPACK                       3        /* BMP  */
#define A_BLOODLUST                      4        /* BMP  */
#define A_BLOODLUST1                     5        /* BMP  */
#define A_BLOODLUST2                     6        /* BMP  */
#define A_BLOODLUST3                     7        /* BMP  */
#define A_BLOODLUST4                     8        /* BMP  */
#define A_BLOODLUST5                     9        /* BMP  */
#define A_BULLET                         10       /* BMP  */
#define A_CHICKEN                        11       /* BMP  */
#define A_COKE                           12       /* BMP  */
#define A_GOGGLES                        13       /* BMP  */
#define A_GOGGLES1                       14       /* BMP  */
#define A_GOGGLES2                       15       /* BMP  */
#define A_ROCKET                         16       /* BMP  */
#define A_SHELL                          17       /* BMP  */
#define BACKDROP                         18       /* BMP  */
#define BLOB000                          19       /* BMP  */
#define BLOB001                          20       /* BMP  */
#define BLOB002                          21       /* BMP  */
#define BLOB003                          22       /* BMP  */
#define BLOB004                          23       /* BMP  */
#define BLOB005                          24       /* BMP  */
#define BLOB006                          25       /* BMP  */
#define BLOB007                          26       /* BMP  */
#define BLOB008                          27       /* BMP  */
#define BLOB009                          28       /* BMP  */
#define BLOB010                          29       /* BMP  */
#define BLOB011                          30       /* BMP  */
#define BLOB012                          31       /* BMP  */
#define BLOB013                          32       /* BMP  */
#define BLOB014                          33       /* BMP  */
#define BLOB015                          34       /* BMP  */
#define BLOD0                            35       /* BMP  */
#define BLOD1                            36       /* BMP  */
#define BLOD2                            37       /* BMP  */
#define BLOD3                            38       /* BMP  */
#define BLOD4                            39       /* BMP  */
#define BLOD5                            40       /* BMP  */
#define BLOD6                            41       /* BMP  */
#define BLOD7                            42       /* BMP  */
#define BLOD8                            43       /* BMP  */
#define BLOD9                            44       /* BMP  */
#define BLODA                            45       /* BMP  */
#define BLODB                            46       /* BMP  */
#define BLODC                            47       /* BMP  */
#define BLODD                            48       /* BMP  */
#define BLODE                            49       /* BMP  */
#define D_ARM0                           50       /* BMP  */
#define D_ARM1                           51       /* BMP  */
#define D_ARM2                           52       /* BMP  */
#define D_ARM3                           53       /* BMP  */
#define D_ARM4                           54       /* BMP  */
#define D_ARM5                           55       /* BMP  */
#define D_ARM6                           56       /* BMP  */
#define D_ARM7                           57       /* BMP  */
#define D_ARM8                           58       /* BMP  */
#define D_ARM9                           59       /* BMP  */
#define D_ARMA                           60       /* BMP  */
#define D_ARMB                           61       /* BMP  */
#define D_BACK0                          62       /* BMP  */
#define D_BACK1                          63       /* BMP  */
#define D_BACK2                          64       /* BMP  */
#define D_BACK3                          65       /* BMP  */
#define D_BACK4                          66       /* BMP  */
#define D_BACK5                          67       /* BMP  */
#define D_BACK6                          68       /* BMP  */
#define D_BACK7                          69       /* BMP  */
#define D_BACK8                          70       /* BMP  */
#define D_BACK9                          71       /* BMP  */
#define D_HEAD0                          72       /* BMP  */
#define D_HEAD1                          73       /* BMP  */
#define D_HEAD2                          74       /* BMP  */
#define D_HEAD3                          75       /* BMP  */
#define D_HEAD4                          76       /* BMP  */
#define D_HEAD5                          77       /* BMP  */
#define D_HEAD6                          78       /* BMP  */
#define D_HEAD7                          79       /* BMP  */
#define D_HEAD8                          80       /* BMP  */
#define D_HEAD9                          81       /* BMP  */
#define D_HEADA                          82       /* BMP  */
#define D_HEADB                          83       /* BMP  */
#define D_HEADC                          84       /* BMP  */
#define D_HEADD                          85       /* BMP  */
#define D_IMPALE000                      86       /* BMP  */
#define D_IMPALE001                      87       /* BMP  */
#define D_IMPALE002                      88       /* BMP  */
#define D_IMPALE003                      89       /* BMP  */
#define D_IMPALE004                      90       /* BMP  */
#define D_IMPALE005                      91       /* BMP  */
#define D_IMPALE006                      92       /* BMP  */
#define D_IMPALE007                      93       /* BMP  */
#define D_IMPALE008                      94       /* BMP  */
#define D_IMPALE009                      95       /* BMP  */
#define D_IMPALE010                      96       /* BMP  */
#define D_IMPALE011                      97       /* BMP  */
#define D_IMPALE012                      98       /* BMP  */
#define D_IMPALE013                      99       /* BMP  */
#define D_IMPALE014                      100      /* BMP  */
#define D_IMPALE015                      101      /* BMP  */
#define D_IMPALE016                      102      /* BMP  */
#define D_IMPALE017                      103      /* BMP  */
#define D_IMPALE018                      104      /* BMP  */
#define D_IMPALE019                      105      /* BMP  */
#define D_LEGS000                        106      /* BMP  */
#define D_LEGS001                        107      /* BMP  */
#define D_LEGS002                        108      /* BMP  */
#define D_LEGS003                        109      /* BMP  */
#define D_LEGS004                        110      /* BMP  */
#define D_LEGS005                        111      /* BMP  */
#define D_LEGS006                        112      /* BMP  */
#define D_LEGS007                        113      /* BMP  */
#define D_LEGS008                        114      /* BMP  */
#define D_LEGS009                        115      /* BMP  */
#define D_LEGS010                        116      /* BMP  */
#define D_LEGS011                        117      /* BMP  */
#define D_LEGS012                        118      /* BMP  */
#define D_LEGS013                        119      /* BMP  */
#define D_LEGS014                        120      /* BMP  */
#define D_LEGS015                        121      /* BMP  */
#define D_LEGS016                        122      /* BMP  */
#define D_LEGS017                        123      /* BMP  */
#define GAMEPAL                          124      /* PAL  */
#define HEART1                           125      /* BMP  */
#define HEART2                           126      /* BMP  */
#define HEART3                           127      /* BMP  */
#define J_ARROW                          128      /* BMP  */
#define J_BOTTLE                         129      /* BMP  */
#define J_KNIFE                          130      /* BMP  */
#define J_MINE1                          131      /* BMP  */
#define J_MINE2                          132      /* BMP  */
#define J_ROCKET                         133      /* BMP  */
#define L_EXPLO                          134      /* BMP  */
#define L_SPOT                           135      /* BMP  */
#define L_SPOTB                          136      /* BMP  */
#define MINI                             137      /* FONT */
#define P_BODY                           138      /* BMP  */
#define P_BOW0                           139      /* BMP  */
#define P_BOW1                           140      /* BMP  */
#define P_BOW2                           141      /* BMP  */
#define P_BOW3                           142      /* BMP  */
#define P_BOWB0                          143      /* BMP  */
#define P_BOWB1                          144      /* BMP  */
#define P_BOWB2                          145      /* BMP  */
#define P_BOWB3                          146      /* BMP  */
#define P_KNIFE0                         147      /* BMP  */
#define P_KNIFE1                         148      /* BMP  */
#define P_KNIFE2                         149      /* BMP  */
#define P_KNIFE3                         150      /* BMP  */
#define P_KNIFEB0                        151      /* BMP  */
#define P_KNIFEB1                        152      /* BMP  */
#define P_KNIFEB2                        153      /* BMP  */
#define P_KNIFEB3                        154      /* BMP  */
#define P_LEG0                           155      /* BMP  */
#define P_LEG1                           156      /* BMP  */
#define P_LEG2                           157      /* BMP  */
#define P_LEG3                           158      /* BMP  */
#define P_M160                           159      /* BMP  */
#define P_M161                           160      /* BMP  */
#define P_M162                           161      /* BMP  */
#define P_M163                           162      /* BMP  */
#define P_M16B0                          163      /* BMP  */
#define P_M16B1                          164      /* BMP  */
#define P_M16B2                          165      /* BMP  */
#define P_M16B3                          166      /* BMP  */
#define P_MINI0                          167      /* BMP  */
#define P_MINI1                          168      /* BMP  */
#define P_MINI2                          169      /* BMP  */
#define P_MINI3                          170      /* BMP  */
#define P_MINIB0                         171      /* BMP  */
#define P_MINIB1                         172      /* BMP  */
#define P_MINIB2                         173      /* BMP  */
#define P_MINIB3                         174      /* BMP  */
#define P_PISTOL0                        175      /* BMP  */
#define P_PISTOL1                        176      /* BMP  */
#define P_PISTOL2                        177      /* BMP  */
#define P_PISTOL3                        178      /* BMP  */
#define P_PISTOLB0                       179      /* BMP  */
#define P_PISTOLB1                       180      /* BMP  */
#define P_PISTOLB2                       181      /* BMP  */
#define P_PISTOLB3                       182      /* BMP  */
#define P_ROCKET0                        183      /* BMP  */
#define P_ROCKET1                        184      /* BMP  */
#define P_ROCKET2                        185      /* BMP  */
#define P_ROCKET3                        186      /* BMP  */
#define P_ROCKETB0                       187      /* BMP  */
#define P_ROCKETB1                       188      /* BMP  */
#define P_ROCKETB2                       189      /* BMP  */
#define P_ROCKETB3                       190      /* BMP  */
#define P_SHOTGUN0                       191      /* BMP  */
#define P_SHOTGUN1                       192      /* BMP  */
#define P_SHOTGUN2                       193      /* BMP  */
#define P_SHOTGUN3                       194      /* BMP  */
#define P_SHOTGUNB0                      195      /* BMP  */
#define P_SHOTGUNB1                      196      /* BMP  */
#define P_SHOTGUNB2                      197      /* BMP  */
#define P_SHOTGUNB3                      198      /* BMP  */
#define P_UZI0                           199      /* BMP  */
#define P_UZI1                           200      /* BMP  */
#define P_UZI2                           201      /* BMP  */
#define P_UZI3                           202      /* BMP  */
#define P_UZIB0                          203      /* BMP  */
#define P_UZIB1                          204      /* BMP  */
#define P_UZIB2                          205      /* BMP  */
#define P_UZIB3                          206      /* BMP  */
#define PLACE1                           207      /* BMP  */
#define RESPAWN0                         208      /* BMP  */
#define RESPAWN1                         209      /* BMP  */
#define RESPAWN2                         210      /* BMP  */
#define RESPAWN3                         211      /* BMP  */
#define RESPAWN4                         212      /* BMP  */
#define RESPAWN5                         213      /* BMP  */
#define RESPAWN6                         214      /* BMP  */
#define T_BAR                            215      /* BMP  */
#define T_BLA                            216      /* BMP  */
#define T_BLU                            217      /* BMP  */
#define T_CRATE                          218      /* BMP  */
#define T_GRE                            219      /* BMP  */
#define T_LAD                            220      /* BMP  */
#define T_METAL                          221      /* BMP  */
#define T_PUR                            222      /* BMP  */
#define T_RED                            223      /* BMP  */
#define T_SPIKE                          224      /* BMP  */
#define T_WOOD                           225      /* BMP  */
#define TITLE                            226      /* BMP  */
#define TITLE_GR                         227      /* BMP  */
#define UNREAL                           228      /* FONT */
#define W_BOW                            229      /* BMP  */
#define W_KNIFE                          230      /* BMP  */
#define W_M16                            231      /* BMP  */
#define W_MINE                           232      /* BMP  */
#define W_MINI                           233      /* BMP  */
#define W_PISTOL                         234      /* BMP  */
#define W_ROCKET                         235      /* BMP  */
#define W_SHOTGUN                        236      /* BMP  */
#define W_UZI                            237      /* BMP  */
#define WAV_ARR                          238      /* SAMP */
#define WAV_ARR2                         239      /* SAMP */
#define WAV_ARR3                         240      /* SAMP */
#define WAV_ARR4                         241      /* SAMP */
#define WAV_ARR5                         242      /* SAMP */
#define WAV_ARR6                         243      /* SAMP */
#define WAV_BOW                          244      /* SAMP */
#define WAV_DEAD1                        245      /* SAMP */
#define WAV_DEAD2                        246      /* SAMP */
#define WAV_DEAD3                        247      /* SAMP */
#define WAV_DEAD4                        248      /* SAMP */
#define WAV_DEAD5                        249      /* SAMP */
#define WAV_EXPLODE                      250      /* SAMP */
#define WAV_EXPLODE2                     251      /* SAMP */
#define WAV_INCOMING                     252      /* SAMP */
#define WAV_KNIFE                        253      /* SAMP */
#define WAV_LETSPARTY                    254      /* SAMP */
#define WAV_M16                          255      /* SAMP */
#define WAV_MINE                         256      /* SAMP */
#define WAV_MINIGUN                      257      /* SAMP */
#define WAV_PICKUP                       258      /* SAMP */
#define WAV_RIC                          259      /* SAMP */
#define WAV_RIC2                         260      /* SAMP */
#define WAV_ROCKET                       261      /* SAMP */
#define WAV_SELECT                       262      /* SAMP */
#define WAV_SHOTGUN                      263      /* SAMP */
#define WAV_TYPE                         264      /* SAMP */
#define WAV_UZI                          265      /* SAMP */
#define X_EXPLO0                         266      /* BMP  */
#define X_EXPLO1                         267      /* BMP  */
#define XHAIR                            268      /* BMP  */

