/* Allegro datafile object indexes, produced by grabber v3.0 + WIP */
/* Datafile: d:\psyk\wacko\blood.dat */
/* Date: Tue Jun  9 20:05:00 1998 */
/* Do not hand edit! */

#define _COPYR_                          0        /* DATA */
#define A_ARMOUR                         1        /* BMP  */
#define A_ARROW                          2        /* BMP  */
#define A_BACKPACK                       3        /* BMP  */
#define A_BULLET                         4        /* BMP  */
#define A_CHICKEN                        5        /* BMP  */
#define A_COKE                           6        /* BMP  */
#define A_GOGGLES                        7        /* BMP  */
#define A_ROCKET                         8        /* BMP  */
#define A_SHELL                          9        /* BMP  */
#define BACKDROP                         10       /* BMP  */
#define EXPLO1                           11       /* BMP  */
#define EXPLO2                           12       /* BMP  */
#define F_MINI                           13       /* FONT */
#define F_UNREAL                         14       /* FONT */
#define GAMEPAL                          15       /* PAL  */
#define HEART1                           16       /* BMP  */
#define HEART2                           17       /* BMP  */
#define HEART3                           18       /* BMP  */
#define J_ARROW                          19       /* BMP  */
#define J_KNIFE                          20       /* BMP  */
#define J_ROCKET                         21       /* BMP  */
#define MINE1                            22       /* BMP  */
#define MINE2                            23       /* BMP  */
#define P_BODY                           24       /* BMP  */
#define P_BOW0                           25       /* BMP  */
#define P_BOW1                           26       /* BMP  */
#define P_BOW2                           27       /* BMP  */
#define P_BOW3                           28       /* BMP  */
#define P_BOWB0                          29       /* BMP  */
#define P_BOWB1                          30       /* BMP  */
#define P_BOWB2                          31       /* BMP  */
#define P_BOWB3                          32       /* BMP  */
#define P_KNIFE0                         33       /* BMP  */
#define P_KNIFE1                         34       /* BMP  */
#define P_KNIFE2                         35       /* BMP  */
#define P_KNIFE3                         36       /* BMP  */
#define P_KNIFEB0                        37       /* BMP  */
#define P_KNIFEB1                        38       /* BMP  */
#define P_KNIFEB2                        39       /* BMP  */
#define P_KNIFEB3                        40       /* BMP  */
#define P_LEG0                           41       /* BMP  */
#define P_LEG1                           42       /* BMP  */
#define P_LEG2                           43       /* BMP  */
#define P_LEG3                           44       /* BMP  */
#define P_M160                           45       /* BMP  */
#define P_M161                           46       /* BMP  */
#define P_M162                           47       /* BMP  */
#define P_M163                           48       /* BMP  */
#define P_M16B0                          49       /* BMP  */
#define P_M16B1                          50       /* BMP  */
#define P_M16B2                          51       /* BMP  */
#define P_M16B3                          52       /* BMP  */
#define P_MINI0                          53       /* BMP  */
#define P_MINI1                          54       /* BMP  */
#define P_MINI2                          55       /* BMP  */
#define P_MINI3                          56       /* BMP  */
#define P_MINIB0                         57       /* BMP  */
#define P_MINIB1                         58       /* BMP  */
#define P_MINIB2                         59       /* BMP  */
#define P_MINIB3                         60       /* BMP  */
#define P_PISTOL0                        61       /* BMP  */
#define P_PISTOL1                        62       /* BMP  */
#define P_PISTOL2                        63       /* BMP  */
#define P_PISTOL3                        64       /* BMP  */
#define P_PISTOLB0                       65       /* BMP  */
#define P_PISTOLB1                       66       /* BMP  */
#define P_PISTOLB2                       67       /* BMP  */
#define P_PISTOLB3                       68       /* BMP  */
#define P_ROCKET0                        69       /* BMP  */
#define P_ROCKET1                        70       /* BMP  */
#define P_ROCKET2                        71       /* BMP  */
#define P_ROCKET3                        72       /* BMP  */
#define P_ROCKETB0                       73       /* BMP  */
#define P_ROCKETB1                       74       /* BMP  */
#define P_ROCKETB2                       75       /* BMP  */
#define P_ROCKETB3                       76       /* BMP  */
#define P_SHOTGUN0                       77       /* BMP  */
#define P_SHOTGUN1                       78       /* BMP  */
#define P_SHOTGUN2                       79       /* BMP  */
#define P_SHOTGUN3                       80       /* BMP  */
#define P_SHOTGUNB0                      81       /* BMP  */
#define P_SHOTGUNB1                      82       /* BMP  */
#define P_SHOTGUNB2                      83       /* BMP  */
#define P_SHOTGUNB3                      84       /* BMP  */
#define P_UZI0                           85       /* BMP  */
#define P_UZI1                           86       /* BMP  */
#define P_UZI2                           87       /* BMP  */
#define P_UZI3                           88       /* BMP  */
#define P_UZIB0                          89       /* BMP  */
#define P_UZIB1                          90       /* BMP  */
#define P_UZIB2                          91       /* BMP  */
#define P_UZIB3                          92       /* BMP  */
#define PLACE1                           93       /* BMP  */
#define T_BAR                            94       /* BMP  */
#define T_BLA                            95       /* BMP  */
#define T_BLU                            96       /* BMP  */
#define T_CRATE                          97       /* BMP  */
#define T_GRE                            98       /* BMP  */
#define T_LAD                            99       /* BMP  */
#define T_METAL                          100      /* BMP  */
#define T_PUR                            101      /* BMP  */
#define T_RED                            102      /* BMP  */
#define T_SPIKE                          103      /* BMP  */
#define T_WOOD                           104      /* BMP  */
#define W_BOW                            105      /* BMP  */
#define W_KNIFE                          106      /* BMP  */
#define W_M16                            107      /* BMP  */
#define W_MINE                           108      /* BMP  */
#define W_MINI                           109      /* BMP  */
#define W_PISTOL                         110      /* BMP  */
#define W_ROCKET                         111      /* BMP  */
#define W_SHOTGUN                        112      /* BMP  */
#define W_UZI                            113      /* BMP  */
#define XHAIR                            114      /* BMP  */

