/* Allegro datafile object indexes, produced by grabber v3.9.20 (WIP), djgpp */
/* Datafile: c:\psyk\red09\blood.dat */
/* Date: Fri Aug 13 21:38:19 1999 */
/* Do not hand edit! */

#define _COPYR_                          0        /* DATA */
#define A_ARMOUR                         1        /* BMP  */
#define A_ARROW                          2        /* BMP  */
#define A_BACKPACK                       3        /* BMP  */
#define A_BLOODLUST                      4        /* BMP  */
#define A_BLOODLUST1                     5        /* BMP  */
#define A_BLOODLUST2                     6        /* BMP  */
#define A_BLOODLUST3                     7        /* BMP  */
#define A_BLOODLUST4                     8        /* BMP  */
#define A_BLOODLUST5                     9        /* BMP  */
#define A_BULLET                         10       /* BMP  */
#define A_CHICKEN                        11       /* BMP  */
#define A_COKE                           12       /* BMP  */
#define A_GOGGLES                        13       /* BMP  */
#define A_GOGGLES1                       14       /* BMP  */
#define A_GOGGLES2                       15       /* BMP  */
#define A_ROCKET                         16       /* BMP  */
#define A_SCANNER                        17       /* BMP  */
#define A_SHELL                          18       /* BMP  */
#define BACKDROP                         19       /* BMP  */
#define BLOD0                            20       /* BMP  */
#define BLOD1                            21       /* BMP  */
#define BLOD2                            22       /* BMP  */
#define BLOD3                            23       /* BMP  */
#define BLOD4                            24       /* BMP  */
#define BLOD5                            25       /* BMP  */
#define BLOD6                            26       /* BMP  */
#define BLOD7                            27       /* BMP  */
#define BLOD8                            28       /* BMP  */
#define BLOD9                            29       /* BMP  */
#define BLODA                            30       /* BMP  */
#define BLODB                            31       /* BMP  */
#define BLODC                            32       /* BMP  */
#define BLODD                            33       /* BMP  */
#define BLODE                            34       /* BMP  */
#define D_ARM0                           35       /* BMP  */
#define D_ARM1                           36       /* BMP  */
#define D_ARM2                           37       /* BMP  */
#define D_ARM3                           38       /* BMP  */
#define D_ARM4                           39       /* BMP  */
#define D_ARM5                           40       /* BMP  */
#define D_ARM6                           41       /* BMP  */
#define D_ARM7                           42       /* BMP  */
#define D_ARM8                           43       /* BMP  */
#define D_ARM9                           44       /* BMP  */
#define D_ARMA                           45       /* BMP  */
#define D_ARMB                           46       /* BMP  */
#define D_BACK0                          47       /* BMP  */
#define D_BACK1                          48       /* BMP  */
#define D_BACK2                          49       /* BMP  */
#define D_BACK3                          50       /* BMP  */
#define D_BACK4                          51       /* BMP  */
#define D_BACK5                          52       /* BMP  */
#define D_BACK6                          53       /* BMP  */
#define D_BACK7                          54       /* BMP  */
#define D_BACK8                          55       /* BMP  */
#define D_BACK9                          56       /* BMP  */
#define D_FOUNTAIN000                    57       /* BMP  */
#define D_FOUNTAIN001                    58       /* BMP  */
#define D_FOUNTAIN002                    59       /* BMP  */
#define D_FOUNTAIN003                    60       /* BMP  */
#define D_FOUNTAIN004                    61       /* BMP  */
#define D_FOUNTAIN005                    62       /* BMP  */
#define D_FOUNTAIN006                    63       /* BMP  */
#define D_FOUNTAIN007                    64       /* BMP  */
#define D_FOUNTAIN008                    65       /* BMP  */
#define D_FOUNTAIN009                    66       /* BMP  */
#define D_FOUNTAIN010                    67       /* BMP  */
#define D_FOUNTAIN011                    68       /* BMP  */
#define D_FOUNTAIN012                    69       /* BMP  */
#define D_FOUNTAIN013                    70       /* BMP  */
#define D_FOUNTAIN014                    71       /* BMP  */
#define D_FOUNTAIN015                    72       /* BMP  */
#define D_FOUNTAIN016                    73       /* BMP  */
#define D_FOUNTAIN017                    74       /* BMP  */
#define D_FOUNTAIN018                    75       /* BMP  */
#define D_HEAD0                          76       /* BMP  */
#define D_HEAD1                          77       /* BMP  */
#define D_HEAD2                          78       /* BMP  */
#define D_HEAD3                          79       /* BMP  */
#define D_HEAD4                          80       /* BMP  */
#define D_HEAD5                          81       /* BMP  */
#define D_HEAD6                          82       /* BMP  */
#define D_HEAD7                          83       /* BMP  */
#define D_HEAD8                          84       /* BMP  */
#define D_HEAD9                          85       /* BMP  */
#define D_HEADA                          86       /* BMP  */
#define D_HEADB                          87       /* BMP  */
#define D_HEADC                          88       /* BMP  */
#define D_HEADD                          89       /* BMP  */
#define D_IMPALE000                      90       /* BMP  */
#define D_IMPALE001                      91       /* BMP  */
#define D_IMPALE002                      92       /* BMP  */
#define D_IMPALE003                      93       /* BMP  */
#define D_IMPALE004                      94       /* BMP  */
#define D_IMPALE005                      95       /* BMP  */
#define D_IMPALE006                      96       /* BMP  */
#define D_IMPALE007                      97       /* BMP  */
#define D_IMPALE008                      98       /* BMP  */
#define D_IMPALE009                      99       /* BMP  */
#define D_IMPALE010                      100      /* BMP  */
#define D_IMPALE011                      101      /* BMP  */
#define D_IMPALE012                      102      /* BMP  */
#define D_IMPALE013                      103      /* BMP  */
#define D_IMPALE014                      104      /* BMP  */
#define D_IMPALE015                      105      /* BMP  */
#define D_IMPALE016                      106      /* BMP  */
#define D_IMPALE017                      107      /* BMP  */
#define D_IMPALE018                      108      /* BMP  */
#define D_IMPALE019                      109      /* BMP  */
#define D_LEGS000                        110      /* BMP  */
#define D_LEGS001                        111      /* BMP  */
#define D_LEGS002                        112      /* BMP  */
#define D_LEGS003                        113      /* BMP  */
#define D_LEGS004                        114      /* BMP  */
#define D_LEGS005                        115      /* BMP  */
#define D_LEGS006                        116      /* BMP  */
#define D_LEGS007                        117      /* BMP  */
#define D_LEGS008                        118      /* BMP  */
#define D_LEGS009                        119      /* BMP  */
#define D_LEGS010                        120      /* BMP  */
#define D_LEGS011                        121      /* BMP  */
#define D_LEGS012                        122      /* BMP  */
#define D_LEGS013                        123      /* BMP  */
#define D_LEGS014                        124      /* BMP  */
#define D_LEGS015                        125      /* BMP  */
#define D_LEGS016                        126      /* BMP  */
#define D_LEGS017                        127      /* BMP  */
#define FRAGDROP                         128      /* BMP  */
#define GAMEPAL                          129      /* PAL  */
#define HEART1                           130      /* BMP  */
#define HEART2                           131      /* BMP  */
#define HEART3                           132      /* BMP  */
#define J_ARROW                          133      /* BMP  */
#define J_KNIFE                          134      /* BMP  */
#define J_MINE1                          135      /* BMP  */
#define J_MINE2                          136      /* BMP  */
#define J_ROCKET                         137      /* BMP  */
#define L_EXPLO                          138      /* BMP  */
#define L_SPOT                           139      /* BMP  */
#define L_SPOTB                          140      /* BMP  */
#define MINI                             141      /* FONT */
#define P_BODY                           142      /* BMP  */
#define P_BOW0                           143      /* BMP  */
#define P_BOW1                           144      /* BMP  */
#define P_BOW2                           145      /* BMP  */
#define P_BOW3                           146      /* BMP  */
#define P_BOWB0                          147      /* BMP  */
#define P_BOWB1                          148      /* BMP  */
#define P_BOWB2                          149      /* BMP  */
#define P_BOWB3                          150      /* BMP  */
#define P_KNIFE0                         151      /* BMP  */
#define P_KNIFE1                         152      /* BMP  */
#define P_KNIFE2                         153      /* BMP  */
#define P_KNIFE3                         154      /* BMP  */
#define P_KNIFEB0                        155      /* BMP  */
#define P_KNIFEB1                        156      /* BMP  */
#define P_KNIFEB2                        157      /* BMP  */
#define P_KNIFEB3                        158      /* BMP  */
#define P_LEG0                           159      /* BMP  */
#define P_LEG1                           160      /* BMP  */
#define P_LEG2                           161      /* BMP  */
#define P_LEG3                           162      /* BMP  */
#define P_M160                           163      /* BMP  */
#define P_M161                           164      /* BMP  */
#define P_M162                           165      /* BMP  */
#define P_M163                           166      /* BMP  */
#define P_M16B0                          167      /* BMP  */
#define P_M16B1                          168      /* BMP  */
#define P_M16B2                          169      /* BMP  */
#define P_M16B3                          170      /* BMP  */
#define P_MINI0                          171      /* BMP  */
#define P_MINI1                          172      /* BMP  */
#define P_MINI2                          173      /* BMP  */
#define P_MINI3                          174      /* BMP  */
#define P_MINIB0                         175      /* BMP  */
#define P_MINIB1                         176      /* BMP  */
#define P_MINIB2                         177      /* BMP  */
#define P_MINIB3                         178      /* BMP  */
#define P_PISTOL0                        179      /* BMP  */
#define P_PISTOL1                        180      /* BMP  */
#define P_PISTOL2                        181      /* BMP  */
#define P_PISTOL3                        182      /* BMP  */
#define P_PISTOLB0                       183      /* BMP  */
#define P_PISTOLB1                       184      /* BMP  */
#define P_PISTOLB2                       185      /* BMP  */
#define P_PISTOLB3                       186      /* BMP  */
#define P_ROCKET0                        187      /* BMP  */
#define P_ROCKET1                        188      /* BMP  */
#define P_ROCKET2                        189      /* BMP  */
#define P_ROCKET3                        190      /* BMP  */
#define P_ROCKETB0                       191      /* BMP  */
#define P_ROCKETB1                       192      /* BMP  */
#define P_ROCKETB2                       193      /* BMP  */
#define P_ROCKETB3                       194      /* BMP  */
#define P_SHOTGUN0                       195      /* BMP  */
#define P_SHOTGUN1                       196      /* BMP  */
#define P_SHOTGUN2                       197      /* BMP  */
#define P_SHOTGUN3                       198      /* BMP  */
#define P_SHOTGUNB0                      199      /* BMP  */
#define P_SHOTGUNB1                      200      /* BMP  */
#define P_SHOTGUNB2                      201      /* BMP  */
#define P_SHOTGUNB3                      202      /* BMP  */
#define P_UZI0                           203      /* BMP  */
#define P_UZI1                           204      /* BMP  */
#define P_UZI2                           205      /* BMP  */
#define P_UZI3                           206      /* BMP  */
#define P_UZIB0                          207      /* BMP  */
#define P_UZIB1                          208      /* BMP  */
#define P_UZIB2                          209      /* BMP  */
#define P_UZIB3                          210      /* BMP  */
#define PLACE1                           211      /* BMP  */
#define RESPAWN0                         212      /* BMP  */
#define RESPAWN1                         213      /* BMP  */
#define RESPAWN2                         214      /* BMP  */
#define RESPAWN3                         215      /* BMP  */
#define RESPAWN4                         216      /* BMP  */
#define RESPAWN5                         217      /* BMP  */
#define RESPAWN6                         218      /* BMP  */
#define T_BAR                            219      /* BMP  */
#define T_BLA                            220      /* BMP  */
#define T_BLU                            221      /* BMP  */
#define T_CRATE                          222      /* BMP  */
#define T_GRE                            223      /* BMP  */
#define T_LAD                            224      /* BMP  */
#define T_METAL                          225      /* BMP  */
#define T_PUR                            226      /* BMP  */
#define T_RED                            227      /* BMP  */
#define T_SPIKE                          228      /* BMP  */
#define T_WOOD                           229      /* BMP  */
#define TITLE                            230      /* BMP  */
#define UNREAL                           231      /* FONT */
#define W_BOW                            232      /* BMP  */
#define W_KNIFE                          233      /* BMP  */
#define W_M16                            234      /* BMP  */
#define W_MINE                           235      /* BMP  */
#define W_MINI                           236      /* BMP  */
#define W_PISTOL                         237      /* BMP  */
#define W_ROCKET                         238      /* BMP  */
#define W_SHOTGUN                        239      /* BMP  */
#define W_UZI                            240      /* BMP  */
#define WAV_ARR                          241      /* SAMP */
#define WAV_ARR2                         242      /* SAMP */
#define WAV_ARR3                         243      /* SAMP */
#define WAV_ARR4                         244      /* SAMP */
#define WAV_ARR5                         245      /* SAMP */
#define WAV_ARR6                         246      /* SAMP */
#define WAV_BOW                          247      /* SAMP */
#define WAV_DEAD1                        248      /* SAMP */
#define WAV_DEAD2                        249      /* SAMP */
#define WAV_DEAD3                        250      /* SAMP */
#define WAV_DEAD4                        251      /* SAMP */
#define WAV_DEAD5                        252      /* SAMP */
#define WAV_EXPLODE                      253      /* SAMP */
#define WAV_EXPLODEBAR                   254      /* SAMP */
#define WAV_INCOMING                     255      /* SAMP */
#define WAV_KNIFE                        256      /* SAMP */
#define WAV_LETSPARTY                    257      /* SAMP */
#define WAV_M16                          258      /* SAMP */
#define WAV_MINE                         259      /* SAMP */
#define WAV_MINIGUN                      260      /* SAMP */
#define WAV_PICKUP                       261      /* SAMP */
#define WAV_RIC                          262      /* SAMP */
#define WAV_RIC2                         263      /* SAMP */
#define WAV_ROCKET                       264      /* SAMP */
#define WAV_SELECT                       265      /* SAMP */
#define WAV_SHOTGUN                      266      /* SAMP */
#define WAV_TYPE                         267      /* SAMP */
#define WAV_UZI                          268      /* SAMP */
#define X_EXPLO0                         269      /* BMP  */
#define X_EXPLO1                         270      /* BMP  */
#define XHAIR                            271      /* BMP  */
#define XHAIRLCD                         272      /* BMP  */

