#
# Red Pixel stats file -- v0.7 stats (approx.)
# These stats make the games VERY long, with low frag counts.
#
# Make sure the remote machine runs with EXACTLY the same stats,
# or your game will go totally out of sync.
#


#
# Weapons
#

knife_anim	3	knife_reload	20	knife_damage	12
pistol_anim	4	pistol_reload	20	pistol_damage	14
bow_anim	4	bow_reload      28	bow_damage	40
shotgun_anim	6	shotgun_reload  24	shotgun_damage	7
uzi_anim	3	uzi_reload	8	uzi_damage	12
m16_anim	2	m16_reload	5	m16_damage	15
minigun_anim	1	minigun_reload	1	minigun_damage	5
bazooka_anim	6	bazooka_reload	40	bazooka_damage	65
			mine_reload	25	mine_damage	45


#
# Health Food
#

max_health	200
max_armour	300
armour_give	100	armour_respawn	180
chicken_heal	50	chicken_respawn	120
coke_heal	15	coke_respawn	60


# 
# Ammo & pickups
#

bullet_give	30	bullet_respawn	30
shell_give	8	shell_respawn	20
mine_give	1	mine_respawn	90
arrow_give	7	arrow_respawn	50
rocket_give	3	rocket_respawn	70

pistol_give	10	pistol_respawn	60
shotgun_give	4	shotgun_respawn	75
uzi_give	30	uzi_respawn	90
m16_give	40	m16_respawn	105
minigun_give	50	minigun_respawn	150
bow_give	3	bow_respawn	130
bazooka_give	2	bazooka_respawn 150


#
# Powerups
#

bloodlust_timeout	30	bloodlust_respawn	180
goggles_timeout		60	goggles_respawn 	180
scanner_timeout		30	scanner_respawn		180


#
# Tiles
#

tile_health	30
tile_respawn	18
barrel_damage	30
